export const MBTTAGS = [
  'MBT',
  'My Big Toe',
  'LCS',
  'IUOC',
  'FWAU',
  'Avatar',
  'Consciousness',
  'Love',
  'Fear',
  'Ego',
  'Intent',
  'Metaphor',
  'Interpretation',
  'Constraints',
  'Brain',
  'Healing',
  'Remote Viewing',
  'Supernatural',
  'Paranormal',
  'Skills',
  'Abilities',
  'Powers',
  'Cooperation',
  'Culture',
  'Corporations',
  'Government',
  'Society',
  'Larger Consciousness System',
  'Big Picture',
  'Science',
  'Physics',
  'Dogma',
  'Double Slit Experiment',
  'Robert Monroe',
  'TMI',
  'The Monroe Institute',
  'Hemi Sync',
  'Binaural Beats',
  'Philosophy',
  'Religion',
  'Theology',
  'Atheism',
  'Experiments',
  'Exercises',
  'Precautions',
  'Virtual Reality',
  'Reality Frame',
  'Ruleset',
  'PMR',
  'NPMR',
  'Physical Matter Reality',
  'Physical World',
  'Information',
  'Entropy',
  'Evolution',
  'Progress',
  'Growth',
  'Learning',
  'Nudges',
  'Growing Up',
  'Becoming Love',
  'Nonphysical',
  'Non Physical Matter Reality',
  'Entities',
  'Guides',
  'Interface',
  'Awareness',
  'Vegan',
  'Food',
  'Diet',
  'Sickness',
  'Meat',
  'Vegetarian',
  'Alcohol',
  'Drugs',
  'Psychedelics',
  'Entheogens',
  'Chemicals',
  'Man',
  'Woman',
  'Male',
  'Female',
  'Primal',
  'Eastern',
  'Western',
  'Tribes',
  'Buddhism',
  'Buddha',
  'Maya',
  'World',
  'Illusion',
  'Double Blind',
  'Nonlocal',
  'Quantum',
  'Quantum Physics',
  'Special Relativity',
  'General Relativity',
  'Materialism',
  'Particle',
  'Wave',
  'Duality',
  'Wave Function',
  'CUSAC',
  'Probability',
  'Statistical',
  'Database',
  'Past',
  'Future',
  'Time',
  'AUM',
  'AUO',
  'Absolute Unbounded Manifold',
  'Metaphysics',
  'World View',
  'Spirituality',
  'Narrow minded',
  'Reductionist',
  'Academia',
  'Astral Travel',
  'Astral Projection',
  'Astral Plane',
  'Absolute Unified Oneness',
  'Matter',
  'Delayed Choice Quantum Eraser',
  'Which Way Data',
  'Data',
  'Symbols',
  'Rendering',
  'Video Lag',
  'Free Will',
  'Choices',
  'Decision',
  'Decision Space',
  'Choosing',
  'Ethics',
  'Animals',
  'Creatures',
  'Universe',
  'Universal',
  'Unconscious',
  'Ignorance',
  'Politics',
  'Leaders',
  'High Priests',
  'Scientists',
  'Sociology',
  'Psychology',
  'History',
  'Esoteric',
  'Occult',
  'Happiness',
  'Suffering',
  'Depression',
  'Trauma',
  'Mind',
  'Mental Diseases',
  'Retardation',
  'Intelligence',
  'Artificial Intelligence',
  'Machines',
  'Intelligent Machines',
  'Life Forms',
  'Aliens',
  'Technology',
  'Environment',
  'Earth',
  'Simulation',
  'Holographic',
  'Theory',
  'Relations',
  'Relationship',
  'Partnership',
  'Nonviolence',
  'Violence',
  'Cruelty',
  'Uncertainty',
  'Digital',
  'System',
  'Laws',
  'Entropy Reduction Trainer',
  'Big Cheese',
  'Hierarchy',
  'Death',
  'Transformation',
  'Life',
  'Afterlife',
  'Heaven',
  'Hell',
  'Utopia',
  'Racism',
  'Anxiety',
  'Beauty',
  'Beliefs',
  'Blind Belief',
  'Greater Reality',
  'Freedom',
  'Liberation',
  'Bondage',
  'Surrender',
  'Knowledge',
  'Will',
  'Determinism',
  'Paradigm',
  'Paradigm Shift',
  'Tom Campbell',
  'MBT Events',
  'Interviews',
  'Fireside Chat',
  'MBT World Tour',
  'Connection',
  'Interconnections',
  'Senses',
  'Vision',
  'Qualia',
  'Light',
  'Speed of Light',
  'Big Bang',
  'Copy Paste',
  'Origin',
  'Life After Death',
  'Life After Life',
  'Focus',
  'Meditation',
  'Point Consciousness',
  'Tools',
  'Rituals',
  'Program',
  'Computer',
  'Memory',
  'Hate',
  'Delusion',
  'Experience',
  'Soul',
  'Illness',
  'Reality',
  'Dream',
  'Dream State',
  'Training',
  'Akashic Records',
  'Randomness',
  'Probability Distribution',
  'Attention',
  'Letting Go',
  'Non Doing',
  'Trees',
  'Objective Reality',
  'Subjective Reality',
  'Teacher',
  'Learning Lab',
  'Competition',
  'Theory of Everything',
  'Technique',
  'Method',
  'Genetic',
  'DNA',
  'Reproduction',
  'Biology',
  'Communication',
  'Dead People',
  'Deceased',
  'Other Side',
  'Telepathy',
  'Creation',
  'Manipulation',
  'Practices',
  'Oneness',
  'Unity',
  'Mental Noise',
  'Chat Room',
  'Chatter',
  'Imagination',
  'Nonphysical Worlds',
  'Multiverse',
  'Out of Body Experiences',
  'OOBE',
  'Sleep',
  'Health',
  'Children',
  'Childhood',
  'Indoctrination',
  'Parenting',
  'Family',
  'Thought',
  'Thinking',
  'Emotions',
  'Perception',
  'Personality',
  'God',
  'Creator',
  'Belief System',
  'Belief Trap',
  'Guidance',
  'Help',
  'Intellect Level',
  'Being Level',
  'Subconscious',
  'Reincarnation',
  'Rebirth',
  'Past Life',
];
